### ISSUE TITLE
🚀 [Style] - Make a landing page 

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#11]
### Is your feature request related to a problem ? Please describe. ✍️

No

### Describe briefly how you would implement this enhancement.

https://www.figma.com/design/Vc88ZJOcx6QtxS7ARU2l6g/Untitled?t=0RvYpLsxkn4GGxxj-1
Currently, frontend lacks a landing page, I am adding some screenshot and Figma design 
I am also open to what you suggest, maybe drop any good Figma file you have
Try to use radix-ui and its theming system, don't add extra dependencies until it is essential, this is frontend heavy task so this issue may require 2 contributors at the same time or regular communication with me

### Additional context or screenshots

![image](https://github.com/Girishbari/comic-cult/assets/38005544/7907f6ee-ff3c-47d3-a193-159bb457a57e)

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by TenzDelek** [comment]
interested in this issue. can you assign it? @Girishbari

**Comment by TenzDelek** [comment]
have sent a permission request to view the figma file, kindly accept it!!

**Comment by Girishbari** [comment]
done, please check

**Comment by Girishbari** [comment]
I though i made it public

**Comment by Girishbari** [comment]
hi, @TenzDelek  I am also open to any new design you have however, it should match to website's moto

**Comment by TenzDelek** [comment]
<img width="728" alt="image" src="https://github.com/Girishbari/comic-cult/assets/122612557/fb628523-2716-40ac-ba86-6c4b89e0abaa">
@Girishbari  still private, mind sharing the link again here

**Comment by Girishbari** [comment]
check now please

**Comment by TenzDelek** [comment]
can view now

**Comment by Girishbari** [comment]
@TenzDelek  any update

**Comment by TenzDelek** [comment]
@Girishbari  will raise pr today

**Comment by Girishbari** [comment]
that will be great

**Comment by DevjitSikdar** [comment]
Can I work on this issue , I am a GSSOC 24 Contributor . I have experience in designing such landing pages using Figma.

**Comment by Girishbari** [comment]
Sure @DevjitSikdar, make one issue I will then assign it to you
@TenzDelek is working on setting some styles and landing page

we can then make some changes if your figma design matches the topic of our website

**Comment by TenzDelek** [comment]
@Girishbari  do u want the font that you have used in the figma file or the one that is currently in the setup

**Comment by Girishbari** [comment]
the one used in figma file
