### ISSUE TITLE
🚀 [Feature Request] - Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [Girishbari/comic-cult#13]
### Is your feature request related to a problem ? Please describe. ✍️

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

### Describe briefly how you would implement this enhancement.

```bash
I will write an Github Action's workflow that will automatically generate comments by github bot in the issue whenever an new issue is being created.
```

### Additional context or screenshots

![image](https://github.com/Girishbari/comic-cult/assets/50082154/0bc5f5b2-84e7-4ad0-b02c-4227c6f729a7)

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Girishbari** [comment]
sure go ahead

**Comment by sanmarg** [comment]
Task done.

**Comment by Girishbari** [comment]
hi @sanmarg, would also like you to add some greeting message when user creates any new issue

**Comment by Girishbari** [comment]
I have reverted the current pr so you can work on the same branch and issue, let me know if there is any prob

**Comment by sanmarg** [comment]
> hi @sanmarg, would also like you to add some greeting message when user creates any new issue

I have done that only Sir. Could you please explain yourself?

**Comment by Girishbari** [comment]
actually I saw that file is for both pr and issue but some how things are greeting are not coming when users are creating issue 
![image](https://github.com/Girishbari/comic-cult/assets/38005544/cf31baeb-e36e-42c7-b83d-d6b474b3d5cf)

**Comment by sanmarg** [comment]
It's for new users only. The workflow is working you can see it under the actions tab and greetings workflow. You'll see the output as below in the case you mentioned.
![image](https://github.com/Girishbari/comic-cult/assets/50082154/710acabf-b950-404a-820b-c19207c13e37)

And If any other user makes an issue the output will be like below and he/she will get the message.
![image](https://github.com/Girishbari/comic-cult/assets/50082154/5dfdc49a-b656-48d3-9dbf-9741a77810d3)

**Comment by Girishbari** [comment]
this looks good, please push your pr once again I will verify the same

**Comment by sanmarg** [comment]
Done.
