### ISSUE TITLE
⚒️ [Refactor]:  Convert current repo into monrepo

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#14]
### Is your feature request related to a problem ? Please describe. ✍️

Currently project has nextjs and node app in one singular which seems to be workable not good for long run I suggest converting current repo into **mono repo or into workspaces** one could use turborepo, pnpm workspaces
[https://turbo.build/repo/docs/getting-started/add-to-project](url)

Changes will require some code refactoring in node app, so I will be available here once conversion  is done I would guide further

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by prabh1234assla** [comment]
I will be working on this issue. I think I can work on it because of my good know-how of NextJs and related terminologies and migrations and even deployments.

**Comment by Girishbari** [comment]
Sure, go ahead

**Comment by Girishbari** [comment]
hey @prabh1234assla, when you successfully convert this repo, do check backend is running with expected output (take reference from video), there may be some changes required in code as well as I mentioned in  issue

You can use postman and can get all envs from mentioned links

**Comment by prabh1234assla** [comment]
Okay sir I will do the same. Sorry for lapse in time had a wifi cut. Will soon update you on the same.

**Comment by Girishbari** [comment]
hey @prabh1234assla, do you need some assistance on this becoz I want to sort this issue soon

I will be available tomorrow

**Comment by prabh1234assla** [comment]
i was sick for some days... sorry sir... i have worked on this i will be merging this soon... if i need help i will notify...
