### ISSUE TITLE
🚀 [Feat] - add appwrite database instance

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#15]
### Is your feature request related to a problem ? Please describe. ✍️

Refer to this repo [https://github.com/Sanchitbajaj02/palettegram](url), see how appwrite instance is integrated do the same in nodejs

### Describe briefly how you would implement this enhancement.

```bash
Nan
```

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by zeba62** [comment]
I would like to work on this.
Can you please assign me this.

**Comment by Girishbari** [comment]
@zeba62 update me on this until tomorrow
