### ISSUE TITLE
🚀 [Feat] - add the sign up route

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#16]
### Is your feature request related to a problem ? Please describe. ✍️

Update node app with sign-up route, also make sure all the necessary checks are made then only do `res.json({ message: 'success'})`

**REMEMBER**

> not to add any db connection as one issue is already made on it, just make a route and apply checks**

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by karanmanglani** [comment]
@Girishbari I would like to work on this issue.

**Comment by Girishbari** [comment]
sure, but start making route in separate folder rather than in index.ts

**Comment by karanmanglani** [comment]
> sure, but start making route in separate folder rather than in index.ts 

Sure

**Comment by BamaCharanChhandogi** [comment]
Hello @Girishbari, I have been selected as a mentor for your project. I don't see your mail for connecting. 
How we can contribute to your project? let's discuss.
