### ISSUE TITLE
🚀 [labeller] - automate issue labelling

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#19]
### Is your feature request related to a problem ? Please describe. ✍️

I have added `labeler.yml`, but it does not seem to work properly
Update it if required and make one random issue named **labeler checker** I will remove it later, once I verify labeler.yaml is working

### Describe briefly how you would implement this enhancement.

```bash
Nan
```

### Additional context or screenshots

Nan

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by DhruvChadha22** [comment]
I think your labeler.yml has no issues. You just need to create the "triage" label for this repo. 

Reference: [Link](https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues)
![image](https://github.com/Girishbari/comic-cult/assets/153297759/1204d702-496d-4f17-8cfa-a8fdf3800e6d)

**Comment by Girishbari** [comment]
you were right, thx for updating, do you want to be assigned this issue and then you can make a empty PR

**Comment by DhruvChadha22** [comment]
Yes, I would love to. Please assign it to me. Thanks!
