### ISSUE TITLE
📚 [Documentation] - Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Girishbari/comic-cult#23]
### Description ✍️

I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others. 

### Record

- [X] I agree to follow this project's :link: [Contributing Guidlines](https://github.com/Girishbari/comic-cult/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
Looks good, go ahead

**Comment by Girishbari** [comment]
any update @PradnyaGaitonde ?

**Comment by PradnyaGaitonde** [comment]
@Girishbari  Yes will add it by EOD.

**Comment by Aman0413** [comment]
Hi @team,

I'd like to take on this issue. Please assign it to me.

Thanks,
Aman Verma
