### ISSUE TITLE
🚀 [Feature Request] - Landing Page Design (Figma)

### ISSUE THREAD

**Issue by DevjitSikdar** [Girishbari/comic-cult#28]
### Is your feature request related to a problem ? Please describe. ✍️

Enhancement I would like to enhance the landing page design using Figma 

### Additional context or screenshots

Additional context

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Girishbari** [comment]
Assigned

**Comment by DevjitSikdar** [comment]
@Girishbari thnxx for assigning me this issue . I am grateful.

**Comment by DevjitSikdar** [comment]
@Girishbari do we have a logo for the website. If not can  I create a new issue under this?

**Comment by DevjitSikdar** [comment]
@Girishbari 
Is this  landing page works?
Its a raw layout 
![COmic](https://github.com/Girishbari/comic-cult/assets/119114006/9be776bc-00ff-462e-96bf-e60a2988f0e8)

**Comment by Girishbari** [comment]
@DevjitSikdar, this looks amazing probably this page would be good for current homepage 
homepage replacing the current one..
but for the landing page you could take inspiration from this [] Link (https://palettegram.vercel.app/) remember take inspiration of layout not of the styling you can use current styling

**Comment by Aman0413** [comment]
Could you assign to me ?

**Comment by DevjitSikdar** [comment]
@Girishbari ok thanks, I will take inspiration from that.

**Comment by Girishbari** [comment]
@Aman0413, @DevjitSikdar  is working, so I cant assign issue to you

**Comment by Girishbari** [comment]
@DevjitSikdar Update me sooner when you have completed the Figma design

**Comment by DevjitSikdar** [comment]
sure @Girishbari

**Comment by Girishbari** [comment]
@DevjitSikdar update me till night, how much figma design is remaining

**Comment by DevjitSikdar** [comment]
@Girishbari I will try to send u the design by tommorow night , Actually the work got delayed for some circumstances.

**Comment by DevjitSikdar** [comment]
https://www.figma.com/design/noJe9ZZ2f3QUtF16Z8eErG/Untitled?node-id=0-1&t=7SIrtXwhd2OOVTiV-1

@Girishbari I have modified the webpage as u have stated , plzz check and inform if any changes required.

**Comment by Girishbari** [comment]
I have requested access

**Comment by DevjitSikdar** [comment]
yea yea i have given

**Comment by Girishbari** [comment]
@DevjitSikdar  do one thing add a Link in readme

make a table containing Design - Link

make a PR

**Comment by DevjitSikdar** [comment]
Ok I will send the link by tonight in a readme file.I will create a pull request by tonight.

**Comment by DevjitSikdar** [comment]
##🎨✍✨Design Links
<table>
    <tr>
        <th>Design</th>
          ##<th>Link</th>
    </tr>
    <tr>
        <td>Design 1</td>
        <td><a href="https://www.figma.com/design/noJe9ZZ2f3QUtF16Z8eErG/Untitled?node-id=0-1&t=SoiQ7EEFy9ART5JZ-1">Link to Design 1</a></td>
    </tr>
</table>

**Comment by DevjitSikdar** [comment]
@Girishbari i have referenced this issue with update readme.md in #43
