### ISSUE TITLE
🚀 [Feature Request] - Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [Girishbari/comic-cult#35]
### Is your feature request related to a problem ? Please describe. ✍️

Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

### Describe briefly how you would implement this enhancement.

Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Asymtode712** [comment]
@Girishbari please assign me this issue

**Comment by Girishbari** [comment]
yeah this looks good, go ahead with this one
