### ISSUE TITLE
📚 [Documentation] - update setup.md

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#37]
### Description ✍️

Currently we've pnpm installation in setup.md, convert the all the base commands into following

cd comic-cult

install dependencies
npm install 

**run whole project** 
turbo dev

**make sure to have turbo as global dependencies**
npm install turbo --global

**run server only**
cd apps/server && npm run dev

**run client only**
cd apps/client && npm run dev

### Record

- [X] I agree to follow this project's :link: [Contributing Guidlines](https://github.com/Girishbari/comic-cult/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by prabh1234assla** [comment]
pnpm was causing an issue while conversion to the monorepo. So I have kept the package manager to be restricted to one and that is npm. I can efficiently handle this issue, provided my knowledge of repo conversion process; which made me to go through all package.json and package-lock.json dependencies, devdependencies and scripts. So I know where and how the configuration and command changes can be made.

**Comment by Girishbari** [comment]
sure, if you wanna take this up go ahead

**Comment by prabh1234assla** [comment]
ok sure I will be glad to work on this

**Comment by iamkanhaiyakumar** [comment]
I've noticed your project lacks a Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully.
I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

I've done a readme file for another project, you can check my profile, i always give my best.

Can you assign me this task?

Thank u @Girishbari

**Comment by Girishbari** [comment]
@prabh1234assla  update me till night

**Comment by iamkanhaiyakumar** [comment]
Can you assign me this issue I complete tonight. 
Believe me

**Comment by Girishbari** [comment]
assigned @iamkanhaiyakumar, if possible also complete the issue #38 which is related to this issue

**Comment by iamkanhaiyakumar** [comment]
please assigned the issue #38

**Comment by iamkanhaiyakumar** [comment]
Sir can close the issue.

**Comment by iamkanhaiyakumar** [comment]
@Girishbari Sir please lebel this issue
