### ISSUE TITLE
📚 [Documentation] - Update README.md

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#38]
### Description ✍️

I noticed Readme does not have a direct link to set up a project, you can add a link with helpful message in How to contribute

### Record

- [X] I agree to follow this project's :link: [Contributing Guidlines](https://github.com/Girishbari/comic-cult/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by iamkanhaiyakumar** [comment]
I've done many  readme file for another project, you can check my profile, i always give my best.

Can you assign me this task?

Thank u @Girishbari

**Comment by Girishbari** [comment]
assigned

**Comment by Girishbari** [comment]
unassigned as there was no update

**Comment by iamkanhaiyakumar** [comment]
Can you assign me again please.

**Comment by Girishbari** [comment]
assigned

**Comment by iamkanhaiyakumar** [comment]
@Girishbari can you merged my PR.
