### ISSUE TITLE
🚀 [Refactor] - Move all the components from app/component to packages

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#40]
### Is your feature request related to a problem ? Please describe. ✍️

there is a packages folder in Monorepo that can be utilized for all UI components, you will have to move the components and update all the respective import statements

### Describe briefly how you would implement this enhancement.

```bash
nan
```

### Additional context or screenshots

nan

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by prabh1234assla** [comment]
I know how the UI components can be pushed to the packages folder and how they can be utilized for all the client side (frontend components) present within the APPS DIRECTORY. I have worked in creating the repo to monorepo and I know the required know-how on how to migrate common packages like UI components or typescript & eslint configs to the PACKAGES DIRECTORY of given monorepo. I hope my expertise can help me in grabbing the opportunity to work on this issue.

**Comment by Girishbari** [comment]
I have already assigned one issue to you, so let other take this up or if you complete that and merge your pr successfully I would assign this to you

**Comment by prabh1234assla** [comment]
okay yeah I indeed agree with this. Thanks for considering my message though.

**Comment by kart2004** [comment]
Hi @Girishbari, could you please assign this to me, I can get it done quickly.
Thanks in advance!

**Comment by Girishbari** [comment]
sure

**Comment by Girishbari** [comment]
@kart2004 how much work is done, update me till night

**Comment by kart2004** [comment]
Hi @Girishbari, I made a pr which hopefully solves the problem so please check it out. I've moved all files and pages directory from app/components and included it in packages folder and I've made all necessary changes to the import statement.
Thanks.

**Comment by Sujal7ss** [comment]
@Girishbari the labels you are using are incorrect.
It should be gssoc only to be recognized as a GirlScript label

**Comment by Girishbari** [comment]
thx for updating

**Comment by Girishbari** [comment]
also regarding to PR you made, it was not completed and was staled for many days so I had to close, you can make new with all the required changes

**Comment by Sujal7ss** [comment]
I can work on this issue.
Assign this to me

**Comment by Sujal7ss** [comment]
![Screenshot 2024-06-03 184306](https://github.com/Girishbari/comic-cult/assets/104003078/fed177e3-8219-4f16-9d49-216fc4f00739)

Im getting this error. Please help to solve it @Girishbari

**Comment by Girishbari** [comment]
@Sujal7ss  let @kart2004 give one more day if no response then you can start working

**Comment by Girishbari** [comment]
you'll need to install turbo [Link to install](https://turbo.build/repo/docs/installing)

**Comment by Sujal7ss** [comment]
I have installed it.
There is issue with the processor architecture.
I have 64bit system. Ryzen 5 processor.

**Comment by Girishbari** [comment]
Do you have wsl

**Comment by Girishbari** [comment]
Connect with on discord search **girish_bari**

**Comment by prabh1234assla** [comment]
I can do it more rapidly. But since this issue is unassigned to me, I can't work. Assign me this issue so that I can work on it.

**Comment by Girishbari** [comment]
@Sujal7ss do want to take it...?

**Comment by Sujal7ss** [comment]
Yes , just need help in setting the development @Girishbari

**Comment by Girishbari** [comment]
assigned, let me figure out why you're having this issue, while I request @prabh1234assla  if he can help you with solving the same

**Comment by Girishbari** [comment]
sujal can you confirm me turbo is installed by running `turbo --version`

**Comment by Sujal7ss** [comment]
@Girishbari 
![image](https://github.com/Girishbari/comic-cult/assets/104003078/32b7726f-3928-4a1b-b841-2ff2ffdbf0b5)

**Comment by Girishbari** [comment]
@sujal use GITPOD otherwise, you have already cloned the repo so open it in gitpod 

1. connect gitpod with github
2. pull new changes on github first
3. create new workspace in gitpof select clone repo 
4. Give all the permission as describe in the pic
![image](https://github.com/Girishbari/comic-cult/assets/38005544/2ae5bf40-3360-4696-b0af-570b69877045)
![image](https://github.com/Girishbari/comic-cult/assets/38005544/f3a92642-3f32-47ba-8b9a-039a8a9f28a2)
5. follow the **CONTRIBUTION.md** and start contributing

**Comment by Sujal7ss** [comment]
Yeah its working now! @Girishbari 
I need to move the components from app to packages and update the import statements.. am I right?

**Comment by Girishbari** [comment]
yes, also see frontend is working as expected there should a landing page
