### ISSUE TITLE
🚀 [Feature Request] - add a login page

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#44]
### Is your feature request related to a problem ? Please describe. ✍️

while there is #40  pending,  we could add a login page in the frontend note that make use of existing components in component directory

### Describe briefly how you would implement this enhancement.

```bash
N/A
```

### Additional context or screenshots

N/A

### Are you contributing for a program?

GSSoC2024

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sujal7ss** [comment]
Please assign me this issue
