### ISSUE TITLE
🚀 [Feature Request] - add a register page 

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#45]
### Is your feature request related to a problem ? Please describe. ✍️

while there is #40  pending,  we could add a rergister page in the frontend note that make use of existing component that is present in component section

### Describe briefly how you would implement this enhancement.

```bash
N/A
```

### Additional context or screenshots

Additional context

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by Sujal7ss** [comment]
I can work on this. Please assign me this issue
