### ISSUE TITLE
🚀 [Feature Request] - automate copying tags from issue to PR

### ISSUE THREAD

**Issue by Girishbari** [Girishbari/comic-cult#47]
### Is your feature request related to a problem ? Please describe. ✍️

I am little bit unsure if this could be done, but I guess there is always  a **yml** file we could make which adds tags from issue to PR

### Describe briefly how you would implement this enhancement.

```bash
N/A
```

### Additional context or screenshots

N/A

### Are you contributing for a program?

Other

### Code of Conduct

- [X] I have read and agree to the Contributing Guidelines of this project.

**Comment by DhruvChadha22** [comment]
Hi, I would like to work on this issue.

**Comment by Girishbari** [comment]
sure
