### ISSUE TITLE
📚 [Documentation] - Add License

### ISSUE THREAD

**Issue by Priyanshu2631** [Girishbari/comic-cult#53]
### Description ✍️

I want to add MIT License to this repository, please assign the issue under GSSOC'24

### Record

- [X] I agree to follow this project's :link: [Contributing Guidlines](https://github.com/Girishbari/comic-cult/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamkanhaiyakumar** [comment]
I want to add MIT License to this repository, please assign the issue under GSSOC'24 
can you assign me @Girishbari
