### ISSUE TITLE
An Input Field for the User to Add Their email on which they will recieve the Comic PDF.

### ISSUE THREAD

**Issue by irfan-iiitr** [Girishbari/comic-cult#7]
I would Like to Work On This.

**Comment by Girishbari** [comment]
wait for a few days may be we'll not need to use email anymore, if issue #8 is implemented perfectly, until then you can create other issues like make ISSUE-TEMPLATE, make github workflow, there are many things needs to be done with this project

**Comment by irfan-iiitr** [comment]
Sure @Girishbari  Sir ! Will work on the ISSUE_TEMPLATE.
