### ISSUE TITLE
Feature: Download button

### ISSUE THREAD

**Issue by StephenStolk** [Girishbari/comic-cult#8]
Instead of getting it on the email. The user can download it from the page where she/he provides the dialogue.

I want to take up this issue

**Comment by Girishbari** [comment]
sure try it, I implemented it first but res.sendFile() was giving error anywats, implement and then test it if everything works safe and sound remove nodemailer config as well **I will check PR locally then only I will merge it**

**Comment by Girishbari** [comment]
@StephenStolk  are you working on this..?

**Comment by StephenStolk** [comment]
@Girishbari 
Yes, I have been working on it.
I am facing the same error with res.send(). I am brainstorming another way right now.

**Comment by Girishbari** [comment]
okay take your time, will figure out things otherwise

**Comment by Girishbari** [comment]
@StephenStolk, any update

**Comment by prayush27** [comment]
Hey, could you assign the labels to this issue?

**Comment by Girishbari** [comment]
Hey @StephenStolk, update me until tomorrow or I will reassign issue to somebody else

**Comment by StephenStolk** [comment]
@Girishbari 
I am not able to find the solution. You can assign to someone else for the solution.
