### ISSUE TITLE
Creation of ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by irfan-iiitr** [Girishbari/comic-cult#9]
Creation of Template for Issues: 
- [ ] Feature Request
- [ ] Bug Report
- [ ] Documentaion

**Comment by irfan-iiitr** [comment]
Please assign me this @Girishbari .

**Comment by Girishbari** [comment]
assigned

**Comment by irfan-iiitr** [comment]
@Girishbari Please add GSSOC Label to it.
